Repository newrelic/newrelic-php-agent, pull requests merged in 2022-07, with the labels that each got.

#492 chore(agent/daemon): Update flatbuffers for flatc v2.0.6
  protocol/flatbuffers/protocol.fbs
  src/newrelic/commands.go
  src/newrelic/protocol/App.go
  src/newrelic/protocol/AppReply.go
  src/newrelic/protocol/AppStatus.go
  src/newrelic/protocol/Error.go
  src/newrelic/protocol/Event.go
  src/newrelic/protocol/Message.go
  src/newrelic/protocol/MessageBody.go
  src/newrelic/protocol/Metric.go
  src/newrelic/protocol/MetricData.go
  src/newrelic/protocol/SlowSQL.go
  src/newrelic/protocol/SpanBatch.go
  src/newrelic/protocol/Trace.go
  src/newrelic/protocol/Transaction.go
  src/newrelic/protocol/encode.go
Labels: ready for review

#488 feat(agent): add logging configuration options
  agent/php_minit.c
  agent/php_newrelic.h
  agent/php_nrini.c
  agent/php_txn.c
  agent/scripts/newrelic.ini.template
  axiom/nr_limits.h
  axiom/nr_txn.h
Labels: ready for review, logging

#496 docs: refactor/formatting of dev env guide
  docs/dev_environment.md
Labels: documentation
