Repository newrelic/newrelic-php-agent, pull requests merged in 2023-11, with the labels that each got.

#750 fix(agent): Resolve mysqli deprecation warnings on PHP 8.1+
  agent/php_internal_instrument.c
  tests/integration/mysqli/test_null_connect_proc.php
  tests/integration/mysqli/test_null_construct_oo.php
  tests/integration/mysqli/test_null_rc_oo.php
  tests/integration/mysqli/test_null_rc_proc.php
  tests/integration/mysqli/test_null_stmt_construct.php
Labels: ready for review, bugfix

#755 fix(agent): Addressed zpp/arginfo mismatches
  agent/php_newrelic.c
Labels: ready for review

#754 feat(agent, axiom): Add php package information to transaction
  agent/fw_laravel.c
  axiom/Makefile
  axiom/nr_php_packages.c
  axiom/nr_php_packages.h
  axiom/nr_txn.c
  axiom/nr_txn.h
  axiom/tests/test_php_packages.c
  axiom/tests/test_txn.c
Labels: ready for review, vuln-mgmt

#762 chore: Update repolinter related items
  .github/workflows/repolinter.yml
  README.md
Labels: ready for review

#766 refactor(agent): improve magic file recognition performance
  agent/php_agent.h
  agent/php_execute.c
  axiom/tests/test_strings.c
  axiom/util_strings.h
Labels: wp-optimization
