Repository newrelic/newrelic-php-agent, pull requests merged in 2023-12, with the labels that each got.

#777 refactor: compile wordpress hook regex at minit
  agent/fw_wordpress.c
  agent/fw_wordpress.h
  agent/php_minit.c
  agent/php_mshutdown.c
  agent/php_newrelic.h
  agent/php_rinit.c
  agent/php_rshutdown.c
Labels: wp-optimization, wp-optimization-beta2, ready-for-merge

#778 refactor: cache wordpress clean tag values
  agent/fw_wordpress.c
  agent/php_newrelic.h
  agent/php_rshutdown.c
Labels: wp-optimization, wp-optimization-beta2, ready-for-merge

#789 refactor: suggestion to #765
  agent/fw_wordpress.c
  agent/php_agent.h
  axiom/tests/test_matcher.c
  axiom/util_matcher.c
  axiom/util_matcher.h
  axiom/util_strings.h
Labels: wp-optimization, wp-optimization-beta2

#769 refactor: only call cufa callback when needed
  agent/fw_drupal.c
  agent/fw_drupal8.c
  agent/fw_wordpress.c
  agent/php_newrelic.h
  agent/php_rinit.c
  agent/php_vm.c
  agent/tests/test_internal_instrument.c
Labels: wp-optimization, wp-optimization-beta2, ready-for-merge

#796 style: fix indentation
  agent/fw_wordpress.c
Labels: ready for review, wp-optimization

#760 feat: send PHP packages info to backend
  axiom/cmd_txndata_transmit.c
  axiom/nr_commands_private.h
  axiom/tests/test_cmd_txndata.c
  axiom/tests/test_php_packages.c
  protocol/flatbuffers/protocol.fbs
  src/newrelic/collector/collector.go
  src/newrelic/commands.go
  src/newrelic/harvest.go
  src/newrelic/php_packages.go
  src/newrelic/php_packages_test.go
  src/newrelic/processor.go
  src/newrelic/processor_test.go
  src/newrelic/protocol/Transaction.go
Labels: ready for review, vuln-mgmt

#782 tests: add EXPECT_PHP_PACKAGES to integration tests
  src/integration_runner/reports.go
  src/newrelic/integration/parse.go
  src/newrelic/integration/php_packages.go
  src/newrelic/integration/test.go
Labels: ready for review, vuln-mgmt
