Repository newrelic/newrelic-php-agent, pull requests merged in 2023-09, with the labels that each got.

#724 fix(agent): Fixes 8T distributed traces
  axiom/nr_segment.c
  axiom/tests/test_segment.c
Labels: bug, ready for review

#719 feat: add functionality to group errors
  agent/php_api.c
  agent/php_api.h
  agent/php_error.c
  agent/php_newrelic.c
  agent/php_newrelic.h
  agent/php_rinit.c
  tests/integration/api/error_group_callback/test_error_group_callback_bad_callback.php
  tests/integration/api/error_group_callback/test_error_group_callback_bad_callback.php7.php
  tests/integration/api/error_group_callback/test_error_group_callback_bad_params.php
  tests/integration/api/error_group_callback/test_error_group_callback_bad_return_null.php
  tests/integration/api/error_group_callback/test_error_group_callback_bad_return_num.php
  tests/integration/api/error_group_callback/test_error_group_callback_clobber.php
  tests/integration/api/error_group_callback/test_error_group_callback_empty_callback.php
  tests/integration/api/error_group_callback/test_error_group_callback_error_non_web.php
  tests/integration/api/error_group_callback/test_error_group_callback_error_web.php
  tests/integration/api/error_group_callback/test_error_group_callback_exception_non_web.php
  tests/integration/api/error_group_callback/test_error_group_callback_exception_web.php
  tests/integration/api/error_group_callback/test_error_group_callback_max_string_len.php
Labels: Errors Inbox

#723 feat: add newrelic_set_user_id API
  agent/php_api.c
  agent/php_api.h
  agent/php_newrelic.c
  tests/integration/api/set_user_id/test_set_user_id.php
  tests/integration/api/set_user_id/test_set_user_id_empty_string.php
  tests/integration/api/set_user_id/test_set_user_id_error.php
  tests/integration/api/set_user_id/test_set_user_id_exceeds_maxlen.php
  tests/integration/api/set_user_id/test_set_user_id_exception.php
  tests/integration/api/set_user_id/test_set_user_id_noarg.php
  tests/integration/api/set_user_id/test_set_user_id_non_string.php
  tests/integration/api/set_user_id/test_set_user_id_null.php
Labels: Errors Inbox

#736 chore(agent): Adds log decoration INI value
  agent/scripts/newrelic.ini.template
Labels: ready for review
