Repository newrelic/newrelic-php-agent, pull requests merged in 2024-01, with the labels that each got.

#775 feat(agent): extract version for php packages
  agent/fw_drupal8.c
  agent/fw_hooks.h
  agent/fw_laminas3.c
  agent/fw_laravel.c
  agent/fw_lumen.c
  agent/fw_slim.c
  agent/fw_symfony4.c
  agent/fw_wordpress.c
  agent/lib_doctrine2.c
  agent/lib_guzzle4.c
  agent/lib_guzzle6.c
  agent/lib_mongodb.c
  agent/lib_monolog.c
  agent/lib_phpunit.c
  agent/lib_predis.c
  agent/php_agent.c
  agent/php_agent.h
  agent/php_execute.c
  axiom/nr_php_packages.c
  axiom/nr_php_packages.h
  axiom/tests/test_txn.c
Labels: ready for review, vuln-mgmt

#798 refactor: improve performance of wrap_generic_callable
  agent/php_execute.c
  agent/php_user_instrument.c
  agent/php_user_instrument.h
  agent/php_wrapper.c
  agent/php_wrapper.h
  agent/php_zval.h
  agent/tests/test_user_instrument.c
  tests/integration/frameworks/drupal/skipif.inc
  tests/integration/frameworks/drupal/test_invoke_all_with.php
  tests/integration/frameworks/drupal/test_module_invoke_all.php
Labels: wp-optimization, ready-for-merge, wp-add-filter, wp-optimization-beta3

#784 refactor: reduce # of wp plugin/theme name calculation
  agent/fw_wordpress.c
  agent/php_user_instrument.h
Labels: wp-optimization, ready-for-merge, wp-add-filter, wp-optimization-beta3

#799 feat: instrument wordpress plugins' callbacks on demand
  agent/fw_wordpress.c
  agent/php_newrelic.h
  agent/php_nrini.c
  agent/scripts/newrelic.ini.template
  tests/integration/frameworks/wordpress/test_wordpress_apply_filters.php
  tests/integration/frameworks/wordpress/test_wordpress_do_action.php
  tests/integration/frameworks/wordpress/test_wordpress_transaction_name_hooks_on.php
Labels: wp-optimization, ready-for-merge, wp-optimization-beta3

#795 feat(daemon): improve logging obfuscation
  src/daemon/main.go
  src/daemon/worker.go
  src/newrelic/collector/client.go
  src/newrelic/collector/collector_test.go
  src/newrelic/processor.go
Labels: ready-for-merge

#802 feat: instrument wordpress core callbacks on demand
  agent/fw_wordpress.c
  agent/php_newrelic.h
  agent/php_nrini.c
  agent/scripts/newrelic.ini.template
  tests/integration/frameworks/wordpress/mock-wordpress-app.php
  tests/integration/frameworks/wordpress/test_wordpress_00.php
  tests/integration/frameworks/wordpress/test_wordpress_00.php7.php
  tests/integration/frameworks/wordpress/test_wordpress_01.php
  tests/integration/frameworks/wordpress/test_wordpress_02.php
  tests/integration/frameworks/wordpress/test_wordpress_03.php
  tests/integration/frameworks/wordpress/test_wordpress_03.php7.php
  tests/integration/frameworks/wordpress/test_wordpress_04.php
  tests/integration/frameworks/wordpress/test_wordpress_04.php7.php
  tests/integration/frameworks/wordpress/test_wordpress_apply_filters.php
  tests/integration/frameworks/wordpress/test_wordpress_do_action.php
  tests/integration/frameworks/wordpress/test_wordpress_slow_hooks_only.php
  tests/integration/frameworks/wordpress/test_wordpress_transaction_name_hooks_on.php
  tests/integration/frameworks/wordpress/wp-config.php
  tests/integration/frameworks/wordpress/wp-content/plugins/mock-plugin1.php
  tests/integration/frameworks/wordpress/wp-content/plugins/mock-plugin2.php
  tests/integration/frameworks/wordpress/wp-content/themes/mock-theme1.php
  tests/integration/frameworks/wordpress/wp-content/themes/mock-theme2.php
  tests/integration/frameworks/wordpress/wp-includes/functions.php
  tests/integration/frameworks/wordpress/wp-includes/plugin.php
  tests/integration/frameworks/wordpress/wp-settings.php
Labels: wp-optimization, wp-optimization-beta3

#815 Release 10.16
  CONTRIBUTING.md
  README.md
  STYLEGUIDE.md
  VERSION
  agent/README.txt
  agent/fw_wordpress.c
  agent/newrelic-install.sh
  agent/php_execute.c
  agent/php_newrelic.h
  agent/php_nrini.c
  agent/php_user_instrument.c
  agent/php_user_instrument.h
  agent/php_wrapper.c
  agent/php_wrapper.h
  agent/php_zval.h
  agent/scripts/newrelic.ini.template
  agent/tests/test_user_instrument.c
  axiom/nr_version.c
  axiom/tests/cross_agent_tests/sql_obfuscation/README.md
  src/daemon/main.go
  src/daemon/worker.go
  src/newrelic/collector/client.go
  src/newrelic/collector/collector_test.go
  src/newrelic/processor.go
  tests/integration/frameworks/drupal/skipif.inc
  tests/integration/frameworks/drupal/test_invoke_all_with.php
  tests/integration/frameworks/drupal/test_module_invoke_all.php
  tests/integration/frameworks/wordpress/mock-wordpress-app.php
  tests/integration/frameworks/wordpress/mock_hooks.php
  tests/integration/frameworks/wordpress/test_wordpress_00.php
  tests/integration/frameworks/wordpress/test_wordpress_00.php7.php
  tests/integration/frameworks/wordpress/test_wordpress_00_1.php
  tests/integration/frameworks/wordpress/test_wordpress_00_2.php
  tests/integration/frameworks/wordpress/test_wordpress_01.php
  tests/integration/frameworks/wordpress/test_wordpress_02.php
  tests/integration/frameworks/wordpress/test_wordpress_03.php
  tests/integration/frameworks/wordpress/test_wordpress_03.php7.php
  tests/integration/frameworks/wordpress/test_wordpress_04.php
  tests/integration/frameworks/wordpress/test_wordpress_04.php7.php
  tests/integration/frameworks/wordpress/test_wordpress_apply_filters.php
  tests/integration/frameworks/wordpress/test_wordpress_do_action.php
  tests/integration/frameworks/wordpress/test_wordpress_slow_hooks_only.php
  tests/integration/frameworks/wordpress/test_wordpress_transaction_name_hooks_on.php
  tests/integration/frameworks/wordpress/wp-config.php
  tests/integration/frameworks/wordpress/wp-content/plugins/mock-plugin1.php
  tests/integration/frameworks/wordpress/wp-content/plugins/mock-plugin2.php
  tests/integration/frameworks/wordpress/wp-content/themes/mock-theme1.php
  tests/integration/frameworks/wordpress/wp-content/themes/mock-theme2.php
  tests/integration/frameworks/wordpress/wp-includes/functions.php
  tests/integration/frameworks/wordpress/wp-includes/plugin.php
  tests/integration/frameworks/wordpress/wp-settings.php
Labels: ready for review

#816 chore: Bump agent to 10.17.0
  VERSION
  axiom/nr_version.c
Labels: ready for review

#817 tests: remove broken exception handling unit tests
  agent/tests/test_php_execute.c
  agent/tests/test_php_wrapper.c
Labels: oapi

#811 fix(agent): revert zend_try/catch php call logic
  agent/php_call.c
Labels: oapi
