Repository newrelic/newrelic-php-agent, pull requests merged in 2024-02, with the labels that each got.

#767 feat(oapi): rework exception handling
  agent/fw_laravel.c
  agent/fw_laravel_queue.c
  agent/fw_lumen.c
  agent/fw_symfony4.c
  agent/php_agent.h
  agent/php_api.c
  agent/php_api.h
  agent/php_api_internal.c
  agent/php_error.c
  agent/php_error.h
  agent/php_execute.c
  agent/php_execute.h
  agent/php_internal_instrument.c
  agent/php_newrelic.h
  agent/php_observer.c
  agent/php_observer.h
  agent/php_stacked_segment.c
  agent/php_stacked_segment.h
  axiom/nr_segment.h
  axiom/nr_txn.c
  axiom/nr_txn.h
  axiom/tests/test_txn.c
  tests/integration/api/distributed_trace/newrelic/test_create_payload_nested_caught_exception.php
  tests/integration/api/distributed_trace/newrelic/test_create_payload_nested_uncaught_exception.php
  tests/integration/api/other/test_end_transaction_nested.php
  tests/integration/api/other/test_end_transaction_nested.php8.php
Labels: oapi-optimization, oapi

#825 refactor: condense exception handling instrumentation
  agent/php_agent.c
  agent/php_agent.h
  agent/php_error.c
  agent/php_execute.c
Labels: oapi

#818 feat(agent): Add INI option that determines if package detection should be enabled
  agent/fw_drupal8.c
  agent/fw_joomla.c
  agent/fw_laminas3.c
  agent/fw_laravel.c
  agent/fw_lumen.c
  agent/fw_magento2.c
  agent/fw_mediawiki.c
  agent/fw_slim.c
  agent/fw_symfony4.c
  agent/fw_wordpress.c
  agent/lib_doctrine2.c
  agent/lib_guzzle4.c
  agent/lib_guzzle6.c
  agent/lib_mongodb.c
  agent/lib_monolog.c
  agent/lib_phpunit.c
  agent/lib_predis.c
  agent/php_execute.c
  agent/php_newrelic.h
  agent/php_nrini.c
  agent/scripts/newrelic.ini.template
  axiom/cmd_txndata_transmit.c
Labels: ready for review, vuln-mgmt

#776 feat(oapi): use segment pool instead of stacked segments
  agent/fw_drupal.c
  agent/lib_zend_http.c
  agent/php_api_datastore.c
  agent/php_execute.c
  agent/php_stacked_segment.c
  agent/php_stacked_segment.h
  agent/php_txn.c
  agent/tests/test_php_stacked_segment.c
Labels: oapi-optimization, oapi

#779 fix: correctly instrument WebdisConnection executeCommand in OAPI
  agent/lib_predis.c
  agent/php_wrapper.h
Labels: oapi

#826 tests: simplify EXPECTED_PHP_PACKAGES "null" value processing
  src/newrelic/integration/parse.go
  src/newrelic/integration/test.go
Labels: ready for review

#827 tests: improve EXPECT_PHP_PACKAGES processing
  src/newrelic/integration/php_packages.go
  src/newrelic/integration/test.go
Labels: ready for review, vuln-mgmt

#828 fix(axiom): handle locale for dt w3c priority
  agent/php_globals.h
  agent/php_minit.c
  agent/php_nrini.c
  agent/php_txn.c
  agent/scripts/newrelic.ini.private.template
  axiom/nr_distributed_trace.c
  axiom/nr_txn.c
  axiom/nr_txn.h
  axiom/tests/test_distributed_trace.c
  files/Dockerfile
  tests/integration/distributed_tracing/w3c/test_insert_dt_headers_locale.php
Labels: bugfix, next-release

#833 fix(agent): ensure package version retrieval does not error out
  agent/fw_drupal8.c
  agent/fw_wordpress.c
Labels: vuln-mgmt

#835 fix(agent): remove PHPUnit version detection
  agent/fw_hooks.h
  agent/lib_phpunit.c
  agent/php_execute.c
Labels: vuln-mgmt

#752 feat(tests): Enable opcache by default for the integration runner.
  src/integration_runner/main.go
  tests/integration/opcache/disabled/opcache_test.inc
  tests/integration/opcache/disabled/skipif.inc
  tests/integration/opcache/disabled/test_computations.php
  tests/integration/opcache/disabled/test_even_odd_count.php
  tests/integration/opcache/disabled/test_recursion_no_segfault.php
  tests/integration/opcache/disabled/test_span_class_function.php
  tests/integration/opcache/disabled/test_span_events_are_created_from_segments.php
  tests/integration/opcache/disabled/test_span_events_are_created_upon_caught_error.php
  tests/integration/opcache/disabled/test_span_events_are_created_upon_exit.php
  tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_error.php
  tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_handled_exception.php
  tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_handled_exception.php7.php
  tests/integration/opcache/disabled/test_span_events_are_created_upon_uncaught_unhandled_exception.php
  tests/integration/opcache/disabled/test_span_events_error_collector_disabled.php
  tests/integration/opcache/disabled/test_span_events_exception_caught_nested.php
  tests/integration/opcache/disabled/test_span_events_exception_caught_nested_rethrown.php
  tests/integration/opcache/disabled/test_span_events_exception_caught_notice_error.php
  tests/integration/opcache/disabled/test_span_events_exception_caught_notice_error_nested.php
  tests/integration/opcache/disabled/test_span_events_exception_caught_same_span.php
  tests/integration/opcache/disabled/test_span_events_exception_uncaught_nested.php
  tests/integration/opcache/disabled/test_span_events_exist_when_no_segments.php
  tests/integration/opcache/disabled/test_span_events_hsm_error.php
  tests/integration/opcache/disabled/test_span_events_notice_error.php
  tests/integration/opcache/disabled/test_span_events_on_dt_off_cat_off.php
  tests/integration/opcache/disabled/test_span_events_on_dt_off_cat_on.php
  tests/integration/opcache/disabled/test_span_events_root_parent.php
  tests/integration/opcache/enabled/test_opcache.php
Labels: ready for review, oapi

#838 fix(agent): fix Lumen detection
  agent/php_execute.c
Labels: ready for review
